Deploy this playbook alongside Slurmscale for automated node image generation

diff --git a/roles/slurmscale/tasks/main.yml b/roles/slurmscale/tasks/main.yml
--- a/roles/slurmscale/tasks/main.yml
+++ b/roles/slurmscale/tasks/main.yml
@@ -138,3 +138,95 @@
     - geerlingguy.repo-epel,1.2.3
     - galaxyproject.cvmfs,0.2.14
     - galaxyproject.slurm,0.1.1
+
+# This is for creating the usegalaxy-node image, but it would probably be ideal if we could just use this playbook for
+# slurmscale itself rather than constructing a quasi-playbook as we do above
+- name: Create Slurm ssh directory
+  file:
+    path: /var/spool/slurm/.ssh
+    state: directory
+    owner: slurm
+    group: slurm
+    mode: 0700
+
+- name: Create Slurm ssh config
+  copy:
+    content: |
+      UserKnownHostsFile /dev/null
+      StrictHostKeyChecking no
+    dest: /var/spool/slurm/.ssh/config
+    owner: slurm
+    group: slurm
+    mode: 0600
+
+- name: Clone Playbook
+  become: yes
+  become_user: slurm
+  git:
+    dest: "{{ slurm_scale_root }}/etc/infrastructure-playbook"
+    recursive: true
+    force: true
+    repo: https://github.com/galaxyproject/infrastructure-playbook.git
+
+- name: Write vault pass
+  copy:
+    content: "{{ vault_pass }}"
+    dest: "{{ slurm_scale_root }}/etc/infrastructure-playbook/.pass"
+    owner: slurm
+    group: slurm
+    mode: 0600
+  no_log: yes
+
+- name: Write clouds.yaml
+  copy:
+    content: "{{ clouds_yaml | to_nice_yaml }}"
+    dest: "{{ slurm_scale_root }}/etc/infrastructure-playbook/clouds.yaml"
+    owner: slurm
+    group: slurm
+    mode: 0600
+  no_log: yes
+
+- name: Install roles
+  become: yes
+  become_user: slurm
+  command: "{{ slurm_scale_root }}/bin/ansible-galaxy role install -p roles -r requirements.yml"
+  args:
+    chdir: "{{ slurm_scale_root }}/etc/infrastructure-playbook"
+
+- name: Write image cleanup script
+  copy:
+    content: |
+      #!/bin/bash
+      export OS_CLOUD=js2
+      cd "{{ slurm_scale_root }}/etc/infrastructure-playbook"
+      while read id name; do
+          case "$name" in
+              usegalaxy-node-*)
+                  echo "Deleting ${name} (${id})"
+                  openstack image delete "$id" || echo "WARNING: Image ${id} failed to delete, but this is ok if it is still in use"
+                  ;;
+          esac
+      done < <(openstack image list --private --format value --column ID --column Name)
+    dest: "{{ slurm_scale_root }}/bin/clean-usegalaxy-node-images"
+    owner: slurm
+    group: slurm
+    mode: 0755
+
+- name: Create image generation cron job
+  cron:
+    cron_file: ansible_slurmscale
+    user: "{{ slurm_scale_user }}"
+    name: usegalaxy-node image
+    hour: 0
+    minute: 0
+    weekday: 0
+    job: ". {{ slurm_scale_root }}/bin/activate && make -C {{ slurm_scale_root }}/etc/infrastructure-playbook usegalaxy-node-image"
+
+- name: Create image cleanup cron job
+  cron:
+    cron_file: ansible_slurmscale
+    user: "{{ slurm_scale_user }}"
+    name: usegalaxy-node image cleanup
+    hour: 23
+    minute: 0
+    job: ". {{ slurm_scale_root }}/bin/activate && {{ slurm_scale_root }}/bin/clean-usegalaxy-node-images"
